apiVersion: v1
appVersion: "19.14"
description: ClickHouse is an open source column-oriented database management system
  capable of real time generation of analytical data reports using SQL queries
home: https://clickhouse.yandex/
icon: https://clickhouse.yandex/images/logo.png
keywords:
- clickhouse
- olap
- database
name: clickhouse
sources:
- https://github.com/sentry-kubernetes/charts
version: 3.1.2
maintainers:
  - name: sentry-kubernetes
