apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 32.2.0
# renovate image=ghcr.io/getsentry/sentry
appVersion: 26.5.0
dependencies:
  - name: memcached
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.9.3
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 17.11.3
    condition: redis.enabled
  - name: kafka
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 29.3.14
    condition: kafka.enabled
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.5.1
    condition: postgresql.enabled
  - name: nginx
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.7.0
    condition: nginx.enabled
maintainers:
  - name: sentry-kubernetes
icon: https://raw.githubusercontent.com/sentry-kubernetes/charts/refs/heads/develop/docs/logo.png
home: https://github.com/sentry-kubernetes/charts
sources:
  - https://github.com/sentry-kubernetes/charts/tree/develop/charts/sentry
