{{- if include "sentry.geodata.enabled" . }}
apiVersion: batch/v1
kind: Job
metadata:
  name: geoip-install-job
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "9"
spec:
  template:
    metadata:
      {{- if .Values.geodata.annotations }}
      annotations:
{{ toYaml .Values.geodata.annotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-geoip
      {{- end }}
      {{- if .Values.geodata.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.geodata.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.geodata.tolerations }}
      tolerations:
{{ toYaml .Values.geodata.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      initContainers:
        - name: init-create-geoip-dir
          image: busybox
          command: ['sh', '-c', 'mkdir -p /usr/share/GeoIP']
          volumeMounts:
            - name: {{ .Values.geodata.volumeName }}
              mountPath: {{ .Values.geodata.mountPath }}
        - name: init-geoip-conf
          image: busybox
          command: ['sh', '-c', 'echo -e "AccountID $(echo $GEOIPUPDATE_ACCOUNT_ID)\nLicenseKey $(echo $GEOIPUPDATE_LICENSE_KEY)\nEditionIDs $(echo $GEOIPUPDATE_EDITION_IDS)" > /usr/share/GeoIP/GeoIP.conf']
          envFrom:
            - secretRef:
                name: {{ include "sentry.geodata.secretName" . }}
          volumeMounts:
            - name: {{ .Values.geodata.volumeName }}
              mountPath: {{ .Values.geodata.mountPath }}
      containers:
        - name: geoipupdate
          image: ghcr.io/maxmind/geoipupdate:v7.0.1
          envFrom:
            - secretRef:
                name: {{ include "sentry.geodata.secretName" . }}
          volumeMounts:
            - name: {{ .Values.geodata.volumeName }}
              mountPath: {{ .Values.geodata.mountPath }}
{{- if .Values.global.volumeMounts }}
{{ toYaml .Values.global.volumeMounts | indent 12 }}
{{- end }}
{{- if .Values.geodata.sidecars }}
{{ toYaml .Values.geodata.sidecars | indent 8 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 8 }}
{{- end }}
      volumes:
      - name: {{ .Values.geodata.volumeName }}
        persistentVolumeClaim:
          claimName: data-sentry-geoip
{{- if .Values.geodata.volumes }}
{{ toYaml .Values.geodata.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
      restartPolicy: OnFailure
{{- end }}
