{{- if .Values.sentry.taskBroker.enabled }}
{{- $root := . }}
{{- range $broker := .Values.sentry.taskBroker.brokers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.fullname" $root }}-taskbroker-{{ $broker.name }}-config
  labels:
    app: {{ template "sentry.fullname" $root }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}"
    release: "{{ $root.Release.Name }}"
    heritage: "{{ $root.Release.Service }}"
    role: taskbroker-{{ $broker.name }}
    {{- include "sentry.component.labels" (dict "component" (printf "taskbroker-%s" $broker.name) "ctx" $root) | nindent 4 }}
  {{- if $root.Values.asHook }}
  annotations:
    meta.helm.sh/release-name: "{{ $root.Release.Name }}"
    meta.helm.sh/release-namespace: "{{ $root.Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "3"
  {{- end }}
data:
  config.yml: |
    {{- include "sentry.taskbroker.configYml" (dict "broker" $broker) | nindent 4 }}
---
{{- end }}
{{- end }}
