{{- if and .Values.sentry.taskBroker.enabled .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}-taskbroker
  labels:
    {{- include "sentry.component.labels" (dict "component" "taskbroker" "ctx" .) | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}


