{{- if and .Values.sentry.genericMetricsConsumer.enabled .Values.sentry.genericMetricsConsumer.autoscaling.enabled }}
apiVersion: {{ template "sentry.autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-generic-metrics-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-generic-metrics-consumer
  minReplicas: {{ .Values.sentry.genericMetricsConsumer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.genericMetricsConsumer.autoscaling.maxReplicas }}
  {{- if eq (include "sentry.autoscaling.apiVersion" .) "autoscaling/v1" }}
  targetCPUUtilizationPercentage: {{ .Values.sentry.genericMetricsConsumer.autoscaling.targetCPUUtilizationPercentage }}
  {{- else if semverCompare ">=1.27-0" .Capabilities.KubeVersion.GitVersion }}
  metrics:
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-generic-metrics-consumer
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.sentry.genericMetricsConsumer.autoscaling.targetCPUUtilizationPercentage }}
  {{- else }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.sentry.genericMetricsConsumer.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
