{{- if and .Values.ingress.enabled .Values.ingress.static.enabled -}}
{{- $root := . -}}
{{- $ingressApiIsStable := eq (include "sentry.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "sentry.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "sentry.ingress.supportsPathType" .) "true" -}}
{{- $defaultPathType := .Values.ingress.pathType | default "ImplementationSpecific" -}}
{{- $ingressPathType := .Values.ingress.static.pathType | default $defaultPathType -}}
{{- $hosts := list .Values.ingress.hostname -}}
{{- range .Values.ingress.additionalHostNames -}}
{{- $hosts = append $hosts . -}}
{{- end -}}
{{- $commonAnnotations := .Values.ingress.annotations | default dict -}}
{{- $staticAnnotations := .Values.ingress.static.annotations | default dict -}}
{{- $annotations := merge (deepCopy $commonAnnotations) $staticAnnotations -}}
{{- $isNginx := eq (default "nginx" .Values.ingress.regexPathStyle) "nginx" -}}
{{- if and $isNginx .Values.ingress.static.enableConfigurationSnippet .Values.ingress.static.configurationSnippet (not (hasKey $annotations "nginx.ingress.kubernetes.io/configuration-snippet")) -}}
{{- $_ := set $annotations "nginx.ingress.kubernetes.io/configuration-snippet" .Values.ingress.static.configurationSnippet -}}
{{- end -}}
apiVersion: {{ include "sentry.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "sentry.fullname" . }}-static
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.labels" . | nindent 4 }}
  {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- range $idx, $host := $hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $root.Values.ingress.static.path | default "/_static/" | quote }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" $root }}-web
                port:
                  {{- if kindIs "float64" $root.Values.service.externalPort }}
                  number: {{ $root.Values.service.externalPort }}
                  {{- else }}
                  name: {{ $root.Values.service.externalPort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" $root }}-web
              servicePort: {{ $root.Values.service.externalPort }}
              {{- end }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
{{- end }}
