{{- if and (.Values.ingress.enabled) (eq (default "nginx" .Values.ingress.regexPathStyle) "gke") }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "sentry.fullname" . }}-web
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.sentry.web.customResponseHeaders }}
  customResponseHeaders:
    headers:
      {{- if .Values.ingress.tls }}
      - "strict-transport-security: max-age=31536000; includeSubDomains"
      {{- end -}}
      {{ toYaml .Values.sentry.web.customResponseHeaders | nindent 6 }}
  {{- end }} 
  healthCheck:
    checkIntervalSec: {{ .Values.sentry.web.probePeriodSeconds }}
    timeoutSec: {{ .Values.sentry.web.probeTimeoutSeconds }}
    healthyThreshold: {{ .Values.sentry.web.probeSuccessThreshold }}
    unhealthyThreshold: {{ .Values.sentry.web.probeFailureThreshold }}  
    type: HTTP
    requestPath: {{ template "sentry.healthCheck.requestPath" }}
    port: {{ .Values.service.externalPort }}
  {{- if .Values.sentry.web.securityPolicy }}
  securityPolicy:
    name: {{ .Values.sentry.web.securityPolicy }}
  {{- end }}
{{- end }}