{{- if .Values.hooks.enabled -}}
{{- $clickhouseHost := include "sentry.clickhouse.host" . -}}
{{- $clickhousePort := include "sentry.clickhouse.port" . -}}
{{- $clickhouseDB := include "sentry.clickhouse.database" . -}}
{{- $clickhouseAuth := include "sentry.clickhouse.auth" . -}}
{{- $clickhouseClusterName := include "sentry.clickhouse.cluster.name" . -}}
{{- $tables := "discover errors groupassignee groupedmessage outcomes_hourly migrations outcomes_mv_hourly outcomes_raw sentry sessions_hourly sessions_hourly_mv sessions_raw transactions" -}}
{{- $dropQuery := "DROP TABLE IF EXISTS ${tbl}_dist" -}}
{{- $createQuery := printf "CREATE TABLE ${tbl}_dist AS ${tbl}_local ENGINE = Distributed('%s', '%s', ${tbl}_local, rand())" $clickhouseClusterName $clickhouseDB -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sentry.fullname" . }}-clickhouse-init
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
    "helm.sh/hook-weight": "6"
spec:
  template:
    metadata:
      name: {{ template "sentry.fullname" . }}-clickhouse-init
      annotations:
        {{- if .Values.hooks.clickhouseInit.podAnnotations }}
{{ toYaml .Values.hooks.clickhouseInit.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      {{- if .Values.clickhouse.clickhouse.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.clickhouse.clickhouse.imagePullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- end }}
      containers:
      - name: clickhouse-init
        image: "{{ .Values.clickhouse.clickhouse.image }}:{{ .Values.clickhouse.clickhouse.imageVersion }}"
        command:
          - /bin/bash
          - -ec
          - >-
            {{- if .Values.clickhouse.enabled }}
            echo "clickhouse-init started"
            
            for tbl in {{ $tables }}; do
              for ((i=0;i<{{ .Values.clickhouse.clickhouse.replicas }};i++)); do
                clickhouse-client {{ $clickhouseAuth }} --database={{ $clickhouseDB }} --host={{ $clickhouseHost }}-$i.{{ $clickhouseHost }}-headless --port={{ $clickhousePort }} --query="{{ $dropQuery }}";
                clickhouse-client {{ $clickhouseAuth }} --database={{ $clickhouseDB }} --host={{ $clickhouseHost }}-$i.{{ $clickhouseHost }}-headless --port={{ $clickhousePort }} --query="{{ $createQuery }}";
                {{- if .Values.clickhouse.clickhouse.configmap.remote_servers.replica.backup.enabled }}
                clickhouse-client {{ $clickhouseAuth }} --database={{ $clickhouseDB }} --host={{ $clickhouseHost }}-replica-$i.{{ $clickhouseHost }}-replica-headless --port={{ $clickhousePort }} --query="{{ $dropQuery }}";
                clickhouse-client {{ $clickhouseAuth }} --database={{ $clickhouseDB }} --host={{ $clickhouseHost }}-replica-$i.{{ $clickhouseHost }}-replica-headless --port={{ $clickhousePort }} --query="{{ $createQuery }}";
                {{- end }}
              done
            done
            
            echo "clickhouse-init finished"
            {{- else }}
            echo "clickhouse-init started"
            
            for tbl in {{ $tables }}; do
              clickhouse-client {{ $clickhouseAuth }} --database={{ $clickhouseDB }} --host={{ $clickhouseHost }} --port={{ $clickhousePort }} --query="{{ $dropQuery }}";
              clickhouse-client {{ $clickhouseAuth }} --database={{ $clickhouseDB }} --host={{ $clickhouseHost }} --port={{ $clickhousePort }} --query="{{ $createQuery }}";
            done
            
            echo "clickhouse-init finished"
            {{- end }}
{{- end }}
