{{- if and .Values.hooks.enabled .Values.hooks.dbCheck.enabled -}}
{{- $clickhouseHost := include "sentry.clickhouse.host" . -}}
{{- $clickhousePort := include "sentry.clickhouse.port" . -}}
{{- $kafkaHost := include "sentry.kafka.host" . -}}
{{- $kafkaPort := include "sentry.kafka.port" . -}}
{{- $kafkaControllerPort := include "sentry.kafka.controller_port" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sentry.fullname" . }}-db-check
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
    "helm.sh/hook-weight": "-1"
spec:
  {{- if .Values.hooks.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ .Values.hooks.activeDeadlineSeconds }}
  {{- end}}
  template:
    metadata:
      name: {{ template "sentry.fullname" . }}-db-check
      annotations:
        {{- if .Values.sentry.worker.annotations }}
{{ toYaml .Values.sentry.worker.annotations | indent 8 }}
        {{- end }}
        {{- if .Values.hooks.dbCheck.podAnnotations }}
{{ toYaml .Values.hooks.dbCheck.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        {{- if .Values.sentry.worker.podLabels }}
{{ toYaml .Values.sentry.worker.podLabels | indent 8 }}
        {{- end }}
        {{- if .Values.hooks.dbCheck.podLabels }}
{{ toYaml .Values.hooks.dbCheck.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.hooks.dbCheck.affinity }}
      affinity:
{{ toYaml .Values.hooks.dbCheck.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.hooks.dbCheck.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.hooks.dbCheck.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.hooks.dbCheck.tolerations }}
      tolerations:
{{ toYaml .Values.hooks.dbCheck.tolerations | indent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.hooks.dbCheck.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.hooks.dbCheck.image.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.hooks.dbCheck.securityContext }}
      securityContext:
{{ toYaml .Values.hooks.dbCheck.securityContext | indent 8 }}
      {{- else }}
      {{- if .Values.hooks.securityContext }}
      securityContext:
{{ toYaml .Values.hooks.securityContext | indent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: db-check
        image: {{ template "dbCheck.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.hooks.dbCheck.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            echo "Checking if clickhouse is up"
            CLICKHOUSE_STATUS=0
            while [ $CLICKHOUSE_STATUS -eq 0 ]; do
              CLICKHOUSE_STATUS=1
              CLICKHOUSE_REPLICAS={{ .Values.clickhouse.enabled | ternary .Values.clickhouse.clickhouse.replicas "1" }}
              i=0; while [ $i -lt $CLICKHOUSE_REPLICAS ]; do
                {{- if .Values.clickhouse.enabled }}
                CLICKHOUSE_HOST={{ $clickhouseHost }}-$i.{{ $clickhouseHost }}-headless
                {{- else }}
                CLICKHOUSE_HOST={{ .Values.externalClickhouse.host }}
                {{- end }}
                if ! nc -z "$CLICKHOUSE_HOST" {{ $clickhousePort }}; then
                  CLICKHOUSE_STATUS=0
                  echo "$CLICKHOUSE_HOST is not available yet"
                fi
                {{- if and .Values.clickhouse.enabled .Values.clickhouse.clickhouse.configmap.remote_servers.replica.backup.enabled }}
                CLICKHOUSE_HOST={{ $clickhouseHost }}-replica-$i.{{ $clickhouseHost }}-replica-headless
                if ! nc -z "$CLICKHOUSE_HOST" {{ $clickhousePort }}; then
                  CLICKHOUSE_STATUS=0
                  echo "$CLICKHOUSE_HOST is not available yet"
                fi
                {{- end }}
                i=$((i+1))
              done
              if [ "$CLICKHOUSE_STATUS" -eq 0 ]; then
                echo "Clickhouse not ready. Sleeping for 10s before trying again"
                sleep 10;
              fi
            done
            echo "Clickhouse is up"

            echo "Checking if kafka is up"
            KAFKA_STATUS=0
            while [ $KAFKA_STATUS -eq 0 ]; do
              KAFKA_STATUS=1
              {{- if .Values.kafka.enabled }}
              KAFKA_REPLICAS={{ .Values.kafka.controller.replicaCount | default 3 }}
              {{- if .Values.kafka.zookeeper.enabled }}
              echo "Kafka Zookeeper is enabled, checking if Zookeeper is up"
              ZOOKEEPER_STATUS=0
              while [ $ZOOKEEPER_STATUS -eq 0 ]; do
                ZOOKEEPER_STATUS=1
                i=0; while [ $i -lt $KAFKA_REPLICAS ]; do
                  ZOOKEEPER_HOST={{ $kafkaHost }}-$i.{{ $kafkaHost }}-headless
                  if ! nc -z "$ZOOKEEPER_HOST" {{ .Values.kafka.zookeeper.port }}; then
                    ZOOKEEPER_STATUS=0
                    echo "$ZOOKEEPER_HOST is not available yet"
                  fi
                  i=$((i+1))
                done
                if [ "$ZOOKEEPER_STATUS" -eq 0 ]; then
                  echo "Zookeeper not ready. Sleeping for 10s before trying again"
                  sleep 10;
                fi
              done
              echo "Zookeeper is up"
              {{- end }}
              {{- if .Values.kafka.kraft.enabled }}
              echo "Kafka Kraft is enabled, checking if Kraft controllers are up"
              KRAFT_STATUS=0
              while [ $KRAFT_STATUS -eq 0 ]; do
                KRAFT_STATUS=1
                i=0; while [ $i -lt $KAFKA_REPLICAS ]; do
                  KRAFT_HOST={{ $kafkaHost }}-controller-$i.{{ $kafkaHost }}-controller-headless
                  if ! nc -z "$KRAFT_HOST" {{ $kafkaControllerPort }}; then
                    KRAFT_STATUS=0
                    echo "$KRAFT_HOST is not available yet"
                  fi
                  i=$((i+1))
                done
                if [ "$KRAFT_STATUS" -eq 0 ]; then
                  echo "Kraft controllers not ready. Sleeping for 10s before trying again"
                  sleep 10;
                fi
              done
              echo "Kraft controllers are up"
              {{- end }}
              {{- else if (not (kindIs "slice" .Values.externalKafka)) }}
              KAFKA_HOST={{ .Values.externalKafka.host }}
              if ! nc -z "$KAFKA_HOST" {{ $kafkaPort }}; then
                KAFKA_STATUS=0
                echo "$KAFKA_HOST is not available yet"
              fi
              {{- else }}
              {{- range $elem := .Values.externalKafka }}
              KAFKA_HOST={{ $elem.host }}
              if ! nc -z "$KAFKA_HOST" {{ $elem.port }}; then
                KAFKA_STATUS=0
                echo "$KAFKA_HOST is not available yet"
              fi
              {{- end }}
              {{- end }}
              if [ "$KAFKA_STATUS" -eq 0 ]; then
                echo "Kafka not ready. Sleeping for 10s before trying again"
                sleep 10;
              fi
            done
            echo "Kafka is up"
{{- if .Values.hooks.dbCheck.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.hooks.dbCheck.volumeMounts | indent 8 }}
{{- end }}
        env:
{{- if .Values.hooks.dbCheck.env }}
{{ toYaml .Values.hooks.dbCheck.env | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.hooks.dbCheck.resources | indent 10 }}
{{- if .Values.hooks.dbCheck.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.hooks.dbCheck.containerSecurityContext | indent 10 }}
{{- end }}
{{- if .Values.hooks.dbCheck.volumes }}
      volumes:
{{ toYaml .Values.hooks.dbCheck.volumes | indent 6 }}
{{- end }}
      {{- if .Values.hooks.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.hooks.shareProcessNamespace }}
      {{- end }}
{{- end }}
