{{- if .Values.hooks.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-migrate
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: {{ template "sentry.fullname" . }}-snuba-migrate
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.annotations }}
{{ toYaml .Values.snuba.annotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        {{- if .Values.snuba.podLabels }}
{{ toYaml .Values.snuba.podLabels | indent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: snuba-migrate
        image: "{{ .Values.images.snuba.repository }}:{{ .Values.images.snuba.tag }}"
        # command: ["./docker_entrypoint.sh", "replacer","--auto-offset-reset=latest","--max-batch-size", "3"]
        command: ["/bin/bash", "-c", "for i in {1..10};do (LOG_LEVEL=debug snuba migrate || true);done"]
        env:
          - name: SNUBA_SETTINGS
            value: /etc/snuba/settings.py
{{- if .Values.snuba.env }}
{{ toYaml .Values.snuba.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        resources:
{{ toYaml .Values.hooks.snubaInit.resources | indent 10 }}
{{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
