apiVersion: v1
appVersion: latest
description: A Helm chart for sentry-kubernetes (https://github.com/getsentry/sentry-kubernetes)
home: https://github.com/getsentry/sentry-kubernetes
icon: https://sentry-brand.storage.googleapis.com/sentry-glyph-white.png
keywords:
- sentry
- report kubernetes events
maintainers:
- email: ctadeu@gmail.com
  name: cpanato
name: sentry-kubernetes
sources:
- https://github.com/getsentry/sentry-kubernetes
version: 0.2.3
