{{- if eq (include "launchpad.enabled" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-launchpad-taskworker
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "launchpad-taskworker" "ctx" .) | nindent 4 }}
  {{- if .Values.asHook }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "25"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.launchpadTaskWorker.replicas }}
  selector:
    matchLabels:
      app: {{ template "sentry.fullname" . }}
      release: "{{ .Release.Name }}"
      role: launchpad-taskworker
  template:
    metadata:
      annotations:
        {{- if .Values.launchpadTaskWorker.annotations }}
{{ toYaml .Values.launchpadTaskWorker.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: launchpad-taskworker
        {{- include "sentry.component.labels" (dict "component" "launchpad-taskworker" "ctx" .) | nindent 8 }}
        {{- if .Values.launchpadTaskWorker.podLabels }}
{{ toYaml .Values.launchpadTaskWorker.podLabels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.images.launchpad.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.launchpad.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.launchpadTaskWorker.affinity }}
      affinity:
{{ toYaml .Values.launchpadTaskWorker.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.launchpadTaskWorker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.launchpadTaskWorker.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.launchpadTaskWorker.tolerations }}
      tolerations:
{{ toYaml .Values.launchpadTaskWorker.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.launchpadTaskWorker.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.launchpadTaskWorker.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.launchpadTaskWorker.securityContext }}
      securityContext:
{{ toYaml .Values.launchpadTaskWorker.securityContext | indent 8 }}
      {{- end }}
      {{- if .Values.launchpadTaskWorker.priorityClassName }}
      priorityClassName: "{{ .Values.launchpadTaskWorker.priorityClassName }}"
      {{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-launchpad-taskworker
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      containers:
      - name: launchpad-taskworker
        image: "{{ template "launchpad.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.launchpad.pullPolicy }}
        command: ["launchpad"]
        args: 
        - worker
        - --verbose
        env:
{{- include "launchpadTaskWorker.env" . | nindent 8 }}
{{- if .Values.launchpadTaskWorker.env }}
{{ toYaml .Values.launchpadTaskWorker.env | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.launchpadTaskWorker.resources | indent 10 }}
{{- if .Values.launchpadTaskWorker.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.launchpadTaskWorker.containerSecurityContext | indent 10 }}
{{- end }}
{{- if .Values.launchpadTaskWorker.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.launchpadTaskWorker.volumeMounts | indent 8 }}
{{- end }}
{{- if .Values.global.volumeMounts }}
{{ toYaml .Values.global.volumeMounts | indent 8 }}
{{- end }}
        livenessProbe:
          exec:
            command:
            - rm
            - /tmp/health.txt
          initialDelaySeconds: {{ default 30 .Values.launchpadTaskWorker.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 10 .Values.launchpadTaskWorker.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ default 5 .Values.launchpadTaskWorker.livenessProbe.timeoutSeconds }}
{{- if .Values.launchpadTaskWorker.sidecars }}
{{ toYaml .Values.launchpadTaskWorker.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
{{- if or .Values.launchpadTaskWorker.volumes .Values.global.volumes }}
      volumes:
{{- if .Values.launchpadTaskWorker.volumes }}
{{ toYaml .Values.launchpadTaskWorker.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
