{{- if and (eq (include "launchpad.enabled" .) "true") .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}-launchpad-taskworker
  labels:
    {{- include "sentry.component.labels" (dict "component" "launchpad-taskworker" "ctx" .) | nindent 4 }}
{{- end }}
