{{- if and (.Values.ingress.enabled) (eq (default "nginx" .Values.ingress.regexPathStyle) "gke") }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "sentry.fullname" . }}-relay
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  {{- if .Values.relay.customResponseHeaders }}
  customResponseHeaders:
    headers:
      {{- if .Values.ingress.tls }}
      - "strict-transport-security: max-age=31536000; includeSubDomains"
      {{- end -}}
      {{ toYaml .Values.relay.customResponseHeaders | nindent 6 }}
  {{- end }}      
  healthCheck:
    checkIntervalSec: {{ .Values.relay.probePeriodSeconds }}
    timeoutSec: {{ .Values.relay.probeTimeoutSeconds }}
    healthyThreshold: {{ .Values.relay.probeSuccessThreshold }}
    unhealthyThreshold: {{ .Values.relay.probeFailureThreshold }}
    type: HTTP
    requestPath: {{ template "relay.healthCheck.requestPath" }}
    port: {{ template "relay.port" . }}
  {{- if .Values.relay.securityPolicy }}
  securityPolicy:
    name: {{ .Values.relay.securityPolicy }}
  {{- end }}
{{- end }}