{{- if and .Values.hooks.enabled .Values.serviceAccount.enabled (not .Values.serviceAccount.shared) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}-hooks
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
