{{- if and (eq (include "launchpad.enabled" .) "true") (not .Values.launchpadTaskWorker.rpcSharedSecret) (not .Values.launchpadTaskWorker.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "launchpad.secretName" . }}
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- if .Values.useArgoCdCompatibleAnnotations }}
    "argocd.argoproj.io/hook": "Sync"
    "argocd.argoproj.io/sync-wave": "-1"
    {{- else }}
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "3"
    {{- end }}
type: Opaque
data:
  rpc-shared-secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
