apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 17.9.2
appVersion: 22.11.0
dependencies:
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 6.1.5
    condition: sourcemaps.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.12.1
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 16.3.2
    condition: kafka.enabled
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 3.2.0
    condition: clickhouse.enabled
  - name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 9.0.0
    condition: zookeeper.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.32.2
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.16.2
    condition: postgresql.enabled
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 12.0.4
    condition: nginx.enabled
maintainers:
  - name: sentry-kubernetes
