apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 21.6.3
appVersion: 24.2.0
dependencies:
  - name: memcached
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 6.5.9
    condition: sourcemaps.enabled
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 17.11.3
    condition: redis.enabled
  - name: kafka
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 23.0.7
    condition: kafka.enabled
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 3.7.1
    condition: clickhouse.enabled
  - name: zookeeper
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.4.11
    condition: zookeeper.enabled
  - name: rabbitmq
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.16.2
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.2.0
    condition: postgresql.enabled
  - name: nginx
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.2.2
    condition: nginx.enabled
maintainers:
  - name: sentry-kubernetes
