apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 3.1.0
appVersion: 10.0.0
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 9.3.2
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 9.0.4
    condition: kafka.enabled
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 1.2.0
    condition: clickhouse.enabled
  - name: rabbitmq-ha
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.38.2
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 8.2.1
    condition: postgresql.enabled
