apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 10.1.0
appVersion: 21.3.0
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 9.3.2
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 12.0.0
    condition: kafka.enabled
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 2.0.0
    condition: clickhouse.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.9.1
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.2.4
    condition: postgresql.enabled
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 6.0.5
    condition: nginx.enabled
