apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 14.0.3
appVersion: 22.3.0
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 15.3.2
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: ~14.2.1
    condition: kafka.enabled
  - name: clickhouse
    repository: https://rubemlrm.com/sentry-kubernetes-charts
    version: 3.1.3
    condition: clickhouse.enabled
  - name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 9.0.0
    condition: clickhouse.enabled,zookeeper.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 8.9.1
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.2.4
    condition: postgresql.enabled
  - name: nginx
    repository: https://charts.bitnami.com/bitnami
    version: 9.3.3
    condition: nginx.enabled
maintainers:
  - name: sentry-kubernetes
