{{- if .Values.clickhouse.configmap.remote_servers.replica.backup.enabled }}
{{- if .Values.clickhouse.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clickhouse.fullname" . }}-replica
  {{- if .Values.clickhouse.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.clickhouse.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}-replica
    app.kubernetes.io/instance: {{ .Release.Name }}-replica
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.clickhouse.metrics.serviceMonitor.selector}}
    {{- toYaml .Values.clickhouse.metrics.serviceMonitor.selector | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clickhouse.name" . }}-replica-metrics
  endpoints:
    - port: metrics
      path: /metrics
      {{- if .Values.clickhouse.metrics.serviceMonitor.interval }}
      interval: {{ .Values.clickhouse.metrics.serviceMonitor.interval }}
      {{- end }}
{{- if .Values.clickhouse.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml .Values.clickhouse.metrics.serviceMonitor.metricRelabelings | indent 6 }}
{{- end }}
{{- if .Values.clickhouse.metrics.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.clickhouse.metrics.serviceMonitor.relabelings | nindent 6 }}
{{- end }}
---
{{- end }}
{{- end }}
