clickhouse:
  fullnameOverride: clickhouse
  clickhouse:
    imageVersion: "19.16"

kafka:
  fullnameOverride: kafka-confluent
  image:
    repository: confluentinc/cp-kafka
    tag: 5.4.0
  extraEnvVars:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka-confluent:9092"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: CONFLUENT_SUPPORT_METRICS_ENABLE
      value: "false"
    - name: KAFKA_LOG4J_LOGGERS
      value: "kafka.cluster=WARN,kafka.controller=WARN,kafka.coordinator=WARN,kafka.log=WARN,kafka.server=WARN,kafka.zookeeper=WARN,state.change.logger=WARN"
    - name: KAFKA_LOG4J_ROOT_LOGLEVEL
      value: "WARN"
    - name: KAFKA_TOOLS_LOG4J_LOGLEVEL
      value: "WARN"
  # replicaCount: 3
  # allowPlaintextListener: true
  # defaultReplicationFactor: 3
  # offsetsTopicReplicationFactor: 3
  # transactionStateLogReplicationFactor: 3
  # transactionStateLogMinIsr: 3

  zookeeper:
    fullnameOverride: zookeeper

redis:
  enabled: true
  fullnameOverride: redis
  
  usePassword: false
  cluster:
    slaveCount: 2
  master:
    nodeSelector: {}
    resources: {}
    # priorityClassName: 
  slave:
    nodeSelector: {}
    resources: {}
    # priorityClassName: 

# redis-ha:
#   enabled: false
#   redis:
#     masterGroupName: master
#     resources: {}
#   sentinel:
#     resources: {}
#   persistentVolume:
#     enabled: true
#     size: 20Gi

global:
  postgresql:
    postgresqlPassword: i@ZBAsFoU4gDz_qDJVX2W8
    postgresqlDatabase: sentry

postgresql:
  enabled: true
  fullnameOverride: postgres
  password: i@ZBAsFoU4gDz_qDJVX2W8 
  # postgresqlUsername: sentry
  postgresqlPassword: i@ZBAsFoU4gDz_qDJVX2W8 
  # password: i@ZBAsFoU4gDz_qDJVX2W8
  postgresqlDatabase: sentry

  replication:
    enabled: true
    slaveReplicas: 2
    synchronousCommit: "on"
    numSynchronousReplicas: 1

rabbitmq-ha:
  enabled: true
  forceBoot: true
  replicaCount: 3
  fullnameOverride: rabbitmq-ha
  rabbitmqErlangCookie: pHgpy3Q6adTskzAT6bLHCFqFTF7lMxhA
  rabbitmqUsername: guest
  rabbitmqPassword: guest

  podDisruptionBudget:
    minAvailable: 1
  
  persistentVolume:
    enabled: true
  resources: {}
  # rabbitmqMemoryHighWatermark: 600MB
  # rabbitmqMemoryHighWatermarkType: absolute

  definitions:
    policies: |-
     {
       "name": "ha-all",
       "pattern": "^((?!celeryev.*).)*$",
       "vhost": "/",
       "definition": {
         "ha-mode": "all",
         "ha-sync-mode": "automatic",
         "ha-sync-batch-size": 1
       }
     }