{{- if (include "sentry.credentials.sentryEnv.enabled" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-env
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "sentry" "ctx" .) | nindent 4 }}
type: Opaque
data:
{{- include "sentry.credentials.sentryEnv.data" . | trim | nindent 2 }}
{{- end }}
