{{- if has "feature-complete" .Values.profiles }}
{{- if .Values.sentry.processSpans.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-process-spans
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "sentry.component.labels" (dict "component" "sentry-process-spans" "ctx" .) | nindent 4 }}
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: sentry
      release: "{{ .Release.Name }}"
      role: sentry-process-spans
  replicas: {{ .Values.sentry.processSpans.replicas }}
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.config" . | sha256sum }}
        {{- if .Values.sentry.processSpans.annotations }}
{{ toYaml .Values.sentry.processSpans.annotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: sentry-process-spans
        {{- include "sentry.component.labels" (dict "component" "sentry-process-spans" "ctx" .) | nindent 8 }}
        {{- if .Values.sentry.processSpans.podLabels }}
{{ toYaml .Values.sentry.processSpans.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.sentry.processSpans.affinity }}
{{ toYaml .Values.sentry.processSpans.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.processSpans.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentry.processSpans.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.processSpans.tolerations }}
      tolerations:
{{ toYaml .Values.sentry.processSpans.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.processSpans.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.sentry.processSpans.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.processSpans.securityContext }}
      securityContext:
{{ toYaml .Values.sentry.processSpans.securityContext | indent 8 }}
      {{- end }}
      initContainers:
{{ include "sentry.initContainer.nodestore-s3" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}-process-spans
        image: "{{ template "sentry.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "consumer"
          - "process-spans"
          - "--consumer-group"
          - "process-spans"
          {{- if .Values.sentry.processSpans.autoOffsetReset }}
          - "--auto-offset-reset"
          - "{{ .Values.sentry.processSpans.autoOffsetReset }}"
          {{- end }}
          {{- if .Values.sentry.processSpans.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          - "--healthcheck-file-path"
          - "/tmp/health.txt"
          {{- if or .Values.sentry.processSpans.concurrency .Values.sentry.processSpans.maxBatchSize .Values.sentry.processSpans.maxBatchTimeMs }}
          - "--"
          {{- end }}
          {{- if .Values.sentry.processSpans.concurrency }}
          - "--processes"
          - "{{ .Values.sentry.processSpans.concurrency }}"
          {{- end }}
          {{- if .Values.sentry.processSpans.maxBatchSize }}
          - "--max-batch-size"
          - "{{ .Values.sentry.processSpans.maxBatchSize }}"
          {{- end }}
          {{- if .Values.sentry.processSpans.maxBatchTimeMs }}
          - "--max-batch-time-ms"
          - "{{ .Values.sentry.processSpans.maxBatchTimeMs }}"
          {{- end }}
        {{- include "sentry.startupProbe.execHealthcheckFile" (dict "startupProbe" .Values.sentry.processSpans.startupProbe "healthcheckFile" "/tmp/health.txt") | nindent 8 }}
        {{- include "sentry.livenessProbe.execHealthcheckFile" (dict "livenessProbe" .Values.sentry.processSpans.livenessProbe "healthcheckFile" "/tmp/health.txt") | nindent 8 }}
        env:
{{ include "sentry.env" . | indent 8 }}
{{ include "sentry.env.nodestore-s3" . | indent 8 }}
{{- if .Values.sentry.processSpans.env }}
{{ toYaml .Values.sentry.processSpans.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: {{ .Values.filestore.filesystem.path }}
          name: sentry-data
{{ include "sentry.volumeMount.replay-filesystem" . | indent 8 }}
{{ include "sentry.volumeMount.nodestore-s3" . | indent 8 }}
        {{- if include "sentry.gcs.secretName" . }}
        - name: sentry-google-cloud-key
          mountPath: /var/run/secrets/google
        {{ end }}
{{- if .Values.sentry.processSpans.volumeMounts }}
{{ toYaml .Values.sentry.processSpans.volumeMounts | indent 8 }}
{{- end }}
{{- if .Values.global.volumeMounts }}
{{ toYaml .Values.global.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.sentry.processSpans.resources | indent 12 }}
{{- if .Values.sentry.processSpans.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.sentry.processSpans.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.sentry.processSpans.sidecars }}
{{ toYaml .Values.sentry.processSpans.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-process-spans
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-sentry
{{ include "sentry.volume.nodestore-s3" . | indent 6 }}
      - name: sentry-data
      {{- if and (eq .Values.filestore.backend "filesystem") .Values.filestore.filesystem.persistence.enabled (.Values.filestore.filesystem.persistence.persistentWorkers) }}
      {{- if .Values.filestore.filesystem.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.filestore.filesystem.persistence.existingClaim }}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "sentry.fullname" . }}-data
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
{{ include "sentry.volume.replay-filesystem" . | indent 6 }}
      {{- if include "sentry.gcs.secretName" . }}
      - name: sentry-google-cloud-key
        secret:
          secretName: {{ include "sentry.gcs.secretName" . }}
      {{ end }}
{{- if .Values.sentry.processSpans.volumes }}
{{ toYaml .Values.sentry.processSpans.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
      {{- if .Values.sentry.processSpans.priorityClassName }}
      priorityClassName: "{{ .Values.sentry.processSpans.priorityClassName }}"
      {{- end }}
{{- end }}
{{- end }}
