{{- if .Values.vroom.autoscaling.enabled }}
apiVersion: {{ template "sentry.autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-vroom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-vroom
  minReplicas: {{ .Values.vroom.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vroom.autoscaling.maxReplicas }}
  {{- if not (eq (include "sentry.autoscaling.apiVersion" .) "autoscaling/v2") }}
  targetCPUUtilizationPercentage: {{ .Values.vroom.autoscaling.targetCPUUtilizationPercentage }}
  {{- else if semverCompare ">=1.27-0" .Capabilities.KubeVersion.GitVersion }}
  metrics:
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-vroom
  {{- else }}
  metrics:
  - type: Resource
    resource:
  {{- end }}
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.vroom.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
