{{- if .Values.sentry.worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-worker
  minReplicas: {{ .Values.sentry.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.worker.autoscaling.maxReplicas }}
  metrics:
  {{- if semverCompare ">=1.27-0" .Capabilities.KubeVersion.GitVersion }}
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-worker
  {{- else }}
  - type: Resource
    resource:
  {{- end }}
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.sentry.worker.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
