{{- if .Values.snuba.api.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-snuba-api
  minReplicas: {{ .Values.snuba.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.snuba.api.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.snuba.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
