{{- if .Values.relay.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-relay
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "25"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-relay
  minReplicas: {{ .Values.relay.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.relay.autoscaling.maxReplicas }}
  metrics:
  {{- if semverCompare ">=1.27-0" .Capabilities.KubeVersion.Version }}
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-relay
  {{- else }}
  - type: Resource
    resource:
  {{- end }}
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.relay.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
