{{- if .Values.sentry.ingestConsumer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-ingest-consumer-attachments
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-ingest-consumer-attachments
  minReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.maxReplicas }}
  metrics:
  {{- if semverCompare ">=1.27-0" .Capabilities.KubeVersion.GitVersion }}
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-ingest-consumer-attachments
  {{- else }}
  - type: Resource
    resource:
  {{- end }}
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.sentry.ingestConsumer.autoscaling.targetCPUUtilizationPercentage }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-ingest-consumer-events
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-ingest-consumer-events
  minReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.maxReplicas }}
  metrics:
  {{- if semverCompare ">=1.27-0" .Capabilities.KubeVersion.GitVersion }}
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-ingest-consumer-events
  {{- else }}
  - type: Resource
    resource:
  {{- end }}
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.sentry.ingestConsumer.autoscaling.targetCPUUtilizationPercentage }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-ingest-consumer-transactions
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-ingest-consumer-transactions
  minReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.ingestConsumer.autoscaling.maxReplicas }}
  metrics:
  {{- if semverCompare ">=1.27-0" .Capabilities.KubeVersion.GitVersion }}
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-ingest-consumer-transactions
  {{- else }}
  - type: Resource
    resource:
  {{- end }}
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.sentry.ingestConsumer.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
