{{- if .Values.vroom.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-vroom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-vroom
  minReplicas: {{ .Values.vroom.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.vroom.autoscaling.maxReplicas }}
  metrics:
  {{- if semverCompare ">=1.27-0" .Capabilities.KubeVersion.GitVersion }}
  - type: ContainerResource
    containerResource:
      container: {{ .Chart.Name }}-vroom
  {{- else }}
  - type: Resource
    resource:
  {{- end }}
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.vroom.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
