---
{{- if .Values.snuba.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-snuba
spec:
  podSelector:
    matchLabels:
      role: snuba
  ingress:
    - ports:
        - port: 1218
          protocol: TCP
  policyTypes:
  - Ingress
{{- end }}
