---
{{- if .Values.sentry.web.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-web
spec:
  podSelector:
    matchLabels:
      role: web
  ingress:
    - ports:
        - port: 9000
          protocol: TCP
  policyTypes:
  - Ingress

{{- end }}
