{{- if and .Values.serviceAccount.enabled ( or .Values.sentry.worker.enabled .Values.sentry.workerEvents.enabled .Values.sentry.workerTransactions.enabled ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}-worker
{{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
