{{- if .Values.clickhouse.ingress.enabled}}
apiVersion: {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }} networking.k8s.io/v1beta1 {{- else }} extensions/v1beta1 {{- end }}
kind: Ingress
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.clickhouse.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.clickhouse.ingress.host }}
      http:
        paths:
        - path: {{ .Values.clickhouse.ingress.path }}
          backend:
            serviceName: {{ include "clickhouse.fullname" . }}
            servicePort: http-port
{{- if .Values.clickhouse.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range .Values.clickhouse.ingress.tls.hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .Values.clickhouse.ingress.tls.secretName }}
{{- end }}
{{- end }}
