{{- if and .Values.clickhouse.metrics.enabled .Values.clickhouse.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "clickhouse.fullname" . }}
  {{- if .Values.clickhouse.metrics.prometheusRule.namespace }}
  namespace: {{ .Values.clickhouse.metrics.prometheusRule.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "clickhouse.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.clickhouse.metrics.prometheusRule.additionalLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.clickhouse.metrics.prometheusRule.rules }}
  groups:
    - name: {{ include "clickhouse.fullname" $ }}
      rules: {{- tpl (toYaml .) $ | nindent 8 }}
  {{- end }}
{{- end }}
