name: Release Please

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please Action
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          config-file: release-please-config.json
