{{- if .Values.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "sentry.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "sentry.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "sentry.ingress.supportsPathType" .) "true" -}}
{{- $ingressPathType := .Values.ingress.pathType | default "ImplementationSpecific" -}}
apiVersion: {{ include "sentry.ingress.apiVersion" . }}
kind: Ingress
metadata:
 name: {{ template "sentry.fullname" . }}
 labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
 annotations:
   {{- range $key, $value := .Values.ingress.annotations }}
     {{ $key }}: {{ $value | quote }}
   {{- end }}
   {{- if eq .Values.ingress.regexPathStyle "nginx" }}
     nginx.ingress.kubernetes.io/use-regex: "true"
   {{- end }}
   {{- if and (eq .Values.ingress.regexPathStyle "aws-alb") (.Values.ingress.alb.httpRedirect) }}
     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
   {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
{{- $hosts := list .Values.ingress.hostname }}
{{- range .Values.ingress.additionalHostNames -}}
{{- $hosts = append $hosts . -}}
{{- end -}}
{{- $outer := . -}}
{{- range $idx, $host := $hosts }}
{{- with $outer }}
    - host: {{ $host }}
      http:
        paths:
    {{- if .Values.nginx.enabled }}
          - path: {{ default "/" .Values.ingress.path | quote }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-nginx
                port:
                  {{- if kindIs "float64" .Values.nginx.service.ports.http }}
                  number: {{ .Values.nginx.service.ports.http }}
                  {{- else }}
                  name: {{ .Values.nginx.service.ports.http }}
                  {{- end }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-nginx
              servicePort: {{ .Values.nginx.service.ports.http }}
              {{- end }}
    {{- else if or (eq (default "nginx" .Values.ingress.regexPathStyle) "aws-alb") (eq (default "nginx" .Values.ingress.regexPathStyle) "gke") }}
    {{- if .Values.ingress.alb.httpRedirect }}
          - path: "/*"
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
              {{- else }}
              serviceName: ssl-redirect
              servicePort: use-annotation
              {{- end }}
    {{- end }}
          - path: /api/0/*
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-web
                port:
                  {{- if kindIs "float64" .Values.service.externalPort }}
                  number: {{ .Values.service.externalPort }}
                  {{- else }}
                  name: {{ .Values.service.externalPort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
              {{- end }}
          - path: /api/*
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-relay
                port:
                  number: {{ template "relay.port" . }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
              {{- end }}
          - path: "/*"
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-web
                port:
                  {{- if kindIs "float64" .Values.service.externalPort }}
                  number: {{ .Values.service.externalPort }}
                  {{- else }}
                  name: {{ .Values.service.externalPort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
              {{- end }}
    {{- else }}
          - path: {{ default "/" .Values.ingress.path }}api/store
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-relay
                port:
                  number: {{ template "relay.port" . }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
              {{- end }}
        {{- if eq (default "nginx" .Values.ingress.regexPathStyle) "traefik" }}
          - path: {{ default "/" .Values.ingress.path }}api/{[1-9][0-9]*}/{(.*)}
        {{- else }}
          - path: {{ default "/" .Values.ingress.path }}api/[1-9][0-9]*/(.*)
        {{- end }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-relay
                port:
                  number: {{ template "relay.port" . }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
              {{- end }}
        {{- if eq (default "nginx" .Values.ingress.regexPathStyle) "traefik" }}
          - path: {{ default "/" .Values.ingress.path }}api/0/relays/{(.*)}
        {{- else }}
          - path: {{ default "/" .Values.ingress.path }}api/0/relays/(.*)
        {{- end }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-relay
                port:
                  number: {{ template "relay.port" . }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-relay
              servicePort: {{ template "relay.port" . }}
              {{- end }}
          - path: {{ default "/" .Values.ingress.path | quote }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "sentry.fullname" . }}-web
                port:
                  {{- if kindIs "float64" .Values.service.externalPort }}
                  number: {{ .Values.service.externalPort }}
                  {{- else }}
                  name: {{ .Values.service.externalPort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ template "sentry.fullname" . }}-web
              servicePort: {{ .Values.service.externalPort }}
              {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
