{{- if eq (include "launchpad.enabled" .) "true" }}
{{- $secretName := include "launchpad.secretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if and $existing (index $existing.data "rpc-shared-secret") }}
  rpc-shared-secret: {{ index $existing.data "rpc-shared-secret" }}
  {{- else }}
  rpc-shared-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
